### PR TITLE
WIP Use SymbolServer.jl

### PR DESCRIPTION
**Pull request by davidanthoff**
Goes hand in hand with https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/276.

### CODE REVIEW

**Comment by ZacLN** [comment]
My main fear is latency (as you mentioned elsewhere). To run linting-type operations we need to check names and types of bindings within modules many thousands of times and I can't see how this could be performant

**Comment by davidanthoff** [comment]
The idea would be that all the symbol info is transferred from the symbol server process into the process where StaticLint.jl runs, and then is cached there. That is what this PR does here: it loads things into the ``store`` of ``StaticLint``, and then all the linting code would access the cached version.

I think for docs we might be able to stomach the latency? Not sure, but maybe worth a try.

The main benefit of all this complication from my point of view would be that we don't have to load user packages into the LS process anymore, which should greatly enhance stability. Plus, we can also support things down the road like switch the active environment for a given workspace: a message could be sent from VS Code to the LS process to use a different environment. LS would kill the current symbol server process, load a new one in the new environment, load all the symbols. But the LS process could just continue to exist without any change.

I do think we probably need some sort of caching in the symbol server, though... I had hoped we could avoid it, but I think that was naive on my part...

**Comment by ZacLN** [comment]
I agree, I don't think caching is avoidable. As currently set up (on the pending julia-vscode branch) the cache is loaded by a process launched through vscode which I think matches the main benefit of this approach.

To handle multiple versions of packages it should be sufficient to mirror the `.ji` versions stored in the `~/.julia/compiled/...` folder. I agree that it would be nice to have this all handled on the julia side of things but I'm slightly wary of keeping another process up and running all the time

**Comment by davidanthoff** [comment]
New attempt at this coming very soon :)

**Pull request closed without merging**
